version: "3.9"
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server_c
    hostname: server_c
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - './server:/app'
      - '/app/node_modules'
    environment:
      - NODE_ENV=development
    networks:
      - iab330
    

  react:
    build: 
      context: ./react/client
      dockerfile: Dockerfile
    container_name: react_c
    hostname: react_c
    restart: always
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
    networks:
      - iab330

networks:
  iab330:
    external: true
    

    
