version: "3.9"
services:
  react:
    build: ./react
    container_name: react-app
    ports:
      - '4000:4000'
    volumes:
      - ./react:/app
      - ./app/node_modules
  server:
    build: ./server
    container_name: server_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

    
