version: "3.9"
services:

  react:
    build: 
      context: ./react/client
      dockerfile: Dockerfile
    container_name: react_c
    hostname: react_c
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./react/client/src:/app/src
      - '/app/node_modules'
    stdin_open: true
    tty: true
    networks:
      - iab330
     

networks:
  iab330:
    external: true
    

    
